<?php
require __DIR__.'/config.php'; require __DIR__.'/functions.php';
// Pastikan HTML Beranda terbaru digunakan setelah pembaruan teks.
if (PHP_SAPI !== 'cli') { header('Cache-Control: no-store, private, max-age=0, must-revalidate'); }
if ($_SERVER['REQUEST_METHOD']!=='GET' && $_SERVER['REQUEST_METHOD']!=='HEAD') { http_response_code(405); header('Allow: GET, HEAD'); exit('Metode tidak diizinkan.'); }
// Hanya agregat yang dirender ke publik; nama, jabatan, NIP dan tanggal lahir
// individual tidak pernah dikirim dalam HTML, atribut data, maupun JavaScript.
$rows=$pdo->query('SELECT status_kepegawaian,nip,tanggal_lahir_manual,jenis_kelamin_manual,mulai_asn_manual,pendidikan_terakhir,jabatan FROM pegawai_distapangtani')->fetchAll();
$analytics=public_analytics($rows); unset($rows);
$dashboard=[];foreach($analytics as $key=>$group)$dashboard[$key]=array_intersect_key($group['all'],array_flip(['total','generations','genders']));
$generationLabels=['X'=>'Generasi X','Y'=>'Generasi Y / Milenial','Z'=>'Generasi Z'];
$generationRanges=['X'=>'1965–1980','Y'=>'1981–1996','Z'=>'1997–2012'];
$genderLabels=['male'=>'Laki-laki','female'=>'Perempuan'];
$counts=[]; foreach(STATUSES as $s) $counts[$s]=$dashboard[$s]['total'];
$total=$dashboard['all']['total'];
$generationTotal=array_sum($dashboard['all']['generations']); $genderTotal=array_sum($dashboard['all']['genders']);
// Fingerprint aset khusus Beranda untuk mencegah CSS/JS lama dari cache browser.
$assetVersion=substr(hash('sha256',hash_file('sha256',__DIR__.'/style.css').hash_file('sha256',__DIR__.'/app.js')),0,12);
page_top('Beranda',null,$assetVersion); ?>
<section class="hero"><div class="hero-copy"><div class="eyebrow"><span class="live-dot"></span> PORTAL INFORMASI PUBLIK</div><h1>Kami, pegawai di dinas yang mengurusi<br><em>ketahanan pangan dan pertanian</em></h1><p>Statistik Kepegawaian di Dinas Ketahanan Pangan dan Pertanian (Distapangtani) Kota Samarinda</p><div class="hero-bottom"><span class="pill">Data langsung dari sistem</span><span><?=e(date_id(new DateTimeImmutable('today')))?></span></div></div><div class="hero-art" aria-hidden="true"><div class="art-ring ring-one"></div><div class="art-ring ring-two"></div><span class="leaf leaf-one"></span><span class="leaf leaf-two"></span><span class="leaf leaf-three"></span><div class="art-stem"></div><span class="art-caption">TUMBUH BERSAMA<br>MELAYANI SAMARINDA</span></div></section>

<div class="section-head"><div><div class="eyebrow muted">GAMBARAN ORGANISASI</div><h2>Komposisi Status Kepegawaian</h2></div><span class="subtle">Empat status, satu pelayanan.</span></div>
<section class="stats" aria-label="Jumlah pegawai"><?php foreach(STATUSES as $i=>$s): ?><article class="stat"><div class="stat-top"><span class="stat-symbol symbol-<?=$i?>"><?=['◎','◈','◷','◇'][$i]?></span><span><?=e($s)?></span></div><strong><?=$counts[$s]?></strong><span class="subtle">pegawai <span class="stat-percent"><?=$total ? round(100*$counts[$s]/$total) : 0?>% dari total</span></span><progress value="<?=$counts[$s]?>" max="<?=max(1,$total)?>" aria-label="Proporsi <?=e($s)?>"></progress></article><?php endforeach ?></section>
<section id="public-dashboard" data-analytics="<?=e(json_encode($analytics,JSON_THROW_ON_ERROR))?>" data-job-labels="<?=e(json_encode(PUBLIC_JOB_LABELS,JSON_THROW_ON_ERROR))?>" data-summary="<?=e(json_encode($dashboard,JSON_THROW_ON_ERROR))?>">
<div class="panel dashboard-controls"><div><div class="eyebrow muted">DASHBOARD DEMOGRAFI</div><h2>Profil pegawai dalam angka</h2><p class="subtle">Pilih statistik umum, latar belakang pendidikan, atau jabatan.</p><nav class="public-tabs" role="tablist" aria-label="Statistik kepegawaian">
<?php foreach(['general'=>'Statistik umum','education'=>'Pendidikan','jobs'=>'Jabatan'] as $key=>$label): ?><button type="button" role="tab" id="tab-<?=$key?>" aria-controls="panel-<?=$key?>" aria-selected="<?=$key==='general'?'true':'false'?>" tabindex="<?=$key==='general'?'0':'-1'?>" data-public-tab="<?=$key?>"><?=e($label)?></button><?php endforeach ?></nav></div><div class="dashboard-filters"><label for="demographic-status">Status kepegawaian<select id="demographic-status"><option value="all">Keseluruhan</option><?php foreach(STATUSES as $s): ?><option value="<?=e($s)?>"><?=e($s)?></option><?php endforeach ?></select></label><label for="analytics-sex">Jenis kelamin<select id="analytics-sex"><option value="all">Semua jenis kelamin</option><option value="male">Laki-laki</option><option value="female">Perempuan</option></select></label><fieldset class="metric-switch"><legend>Tampilan angka</legend><button type="button" class="btn small" data-metric="count" aria-pressed="true">Jumlah</button><button type="button" class="btn small" data-metric="percent" aria-pressed="false">Persentase</button></fieldset></div></div>
<div class="dashboard-context" aria-live="polite"><span id="demographic-context">Keseluruhan · <?=$total?> pegawai</span><span id="demographic-metric-note">Persentase dihitung dari data yang ditampilkan pada masing-masing grafik.</span></div>
<div id="panel-general" role="tabpanel" aria-labelledby="tab-general" tabindex="0">
<div class="demographic-grid">
<section class="panel demographic-card generation-panel" aria-labelledby="generation-heading"><div class="panel-heading"><div><div class="eyebrow muted">BERDASARKAN TAHUN KELAHIRAN</div><h2 id="generation-heading">Komposisi generasi</h2></div><span class="badge neutral">X · Y · Z</span></div><div class="chart-bars"><?php foreach($generationLabels as $key=>$label): $n=$dashboard['all']['generations'][$key]; ?><div class="chart-row" data-group="generations" data-key="<?=e($key)?>"><div class="chart-row-heading"><div><strong><?=e($label)?></strong><small><?=e($generationRanges[$key])?></small></div><output><?=$n?> pegawai</output></div><progress class="generation-<?=e($key)?>" value="<?=$n?>" max="<?=max(1,array_sum($dashboard['all'][isset($generationRanges[$key])?'generations':'genders']))?>" aria-label="<?=e($label)?>: <?=$n?> pegawai"></progress></div><?php endforeach ?></div><p class="chart-footnote">Batas tahun mengacu pada <a href="https://sensus.bps.go.id/topik/tabular/sp2020/2/22/1" target="_blank" rel="noopener noreferrer">klasifikasi generasi BPS</a>. <span id="generation-coverage">Mencakup <?=$generationTotal?> dari <?=$total?> pegawai.</span></p></section>
<section class="panel demographic-card gender-panel" aria-labelledby="gender-heading"><div class="panel-heading"><div><div class="eyebrow muted">BERDASARKAN JENIS KELAMIN</div><h2 id="gender-heading">Komposisi pegawai berdasarkan jenis kelamin</h2></div><span class="badge neutral" id="gender-scope">Keseluruhan</span></div><div class="gender-visual"><svg class="gender-donut" viewBox="0 0 180 180" role="img" aria-label="Proporsi jenis kelamin"><circle class="donut-track" cx="90" cy="90" r="70"/><g transform="rotate(-90 90 90)"><?php $offset=0; foreach(['male','female'] as $genderKey): $share=$genderTotal?100*$dashboard['all']['genders'][$genderKey]/$genderTotal:0; ?><circle class="donut-segment donut-<?=e($genderKey)?>" data-donut="<?=e($genderKey)?>" cx="90" cy="90" r="70" pathLength="100" stroke-dasharray="<?=e($share)?> <?=e(100-$share)?>" stroke-dashoffset="<?=e(-$offset)?>"/><?php $offset+=$share; endforeach ?></g></svg><div class="gender-total"><strong id="demographic-total"><?=$genderTotal?></strong><span>pegawai</span></div></div><div class="chart-bars"><?php foreach($genderLabels as $key=>$label): $n=$dashboard['all']['genders'][$key]; ?><div class="chart-row" data-group="genders" data-key="<?=e($key)?>"><div class="chart-row-heading"><strong><?=e($label)?></strong><output><?=$n?> pegawai</output></div><progress class="gender-<?=e($key)?>" value="<?=$n?>" max="<?=max(1,array_sum($dashboard['all'][isset($generationRanges[$key])?'generations':'genders']))?>" aria-label="<?=e($label)?>: <?=$n?> pegawai"></progress></div><?php endforeach ?></div><p class="chart-footnote"><span id="gender-coverage">Mencakup <?=$genderTotal?> dari <?=$total?> pegawai.</span></p></section>
</div>
<section class="panel insight-panel" aria-labelledby="age-title"><div class="insight-heading"><div><div class="eyebrow muted">AWAL PERJALANAN ASN</div><h2 id="age-title">Usia saat menjadi ASN</h2><p class="subtle">Empat ukuran untuk memahami rentang usia awal pengangkatan.</p></div><span class="badge neutral">Satuan: tahun</span></div>
<div id="age-chart"><?php $age=$analytics['all']['all']['ages']; $ageLabels=['min'=>'Minimum','mean'=>'Rata-rata','median'=>'Median','max'=>'Maksimum']; if($age['n']): ?>
<div class="age-desktop"><?php foreach($ageLabels as $key=>$label): ?><div class="age-row"><span><?=e($label)?></span><progress max="<?=max(1,$age['max'])?>" value="<?=e($age[$key])?>" aria-label="<?=e($label)?>: <?=e(number_format($age[$key],1,',','.'))?> tahun"></progress><strong><?=e(rtrim(rtrim(number_format($age[$key],1,',','.'),'0'),','))?></strong></div><?php endforeach ?></div>
<div class="age-mobile"><svg viewBox="0 0 320 205" role="img" aria-label="Usia awal ASN dalam tahun"><line x1="12" y1="165" x2="308" y2="165" stroke="#cbd8cf"/><?php $i=0;foreach($ageLabels as $key=>$label): $h=120*$age[$key]/max(1,$age['max']);$x=24+76*$i; ?><rect x="<?=$x?>" y="<?=165-$h?>" width="44" height="<?=$h?>" rx="6" fill="<?=['#245b49','#739c80','#b08754','#435f73'][$i]?>"/><text x="<?=$x+22?>" y="<?=153-$h?>" text-anchor="middle" font-size="16" fill="#233e35"><?=e(rtrim(rtrim(number_format($age[$key],1,',','.'),'0'),','))?></text><text x="<?=$x+22?>" y="187" text-anchor="middle" font-size="11" fill="#233e35"><?=e($label)?></text><?php $i++;endforeach ?></svg></div>
<?php else: ?><p class="empty-analytics">Belum ada tanggal lahir dan pengangkatan ASN yang valid.</p><?php endif ?></div><p id="age-coverage" class="insight-note">Dihitung dari <?=$age['n']?> dari <?=$total?> pegawai. Nilai kosong tidak dianggap 0.</p>
<details class="insight-method"><summary>Cara penghitungan</summary><p>Usia dihitung dalam tahun penuh pada tanggal 1 bulan pengangkatan, mengikuti perhitungan Admin. PNS menggunakan bulan/tahun pada NIP; PPPK memakai tanggal mulai ASN yang diisi admin. PJLP tidak termasuk ASN. Tanggal kosong, tidak valid, di masa depan, atau sebelum kelahiran tidak dihitung. Mean adalah jumlah usia dibagi banyak data; median adalah nilai tengah (rata-rata dua nilai tengah untuk jumlah genap).</p></details>
<details class="insight-method"><summary>Bandingkan seluruh status kepegawaian</summary><p class="subtle">Mengikuti filter jenis kelamin; mencakup semua status.</p><div id="age-comparison" class="table-scroll"></div></details></section>
</div>
<section id="panel-education" class="panel insight-panel" role="tabpanel" aria-labelledby="tab-education" tabindex="0" hidden><div class="insight-heading"><div><div class="eyebrow muted">LATAR BELAKANG PENDIDIKAN</div><h2>Pendidikan terakhir pegawai</h2><p class="subtle">Satu pegawai, satu pendidikan terakhir yang tersimpan.</p></div><span class="badge neutral">8 pilihan pendidikan</span></div><div id="education-chart" class="distribution-chart"><?php $educationVisible=array_filter($analytics['all']['all']['education'],fn($n)=>$n>0); $educationTotal=array_sum($educationVisible); foreach($educationVisible as $label=>$n): ?><div class="distribution-row"><div class="distribution-label"><span><?=e($label)?></span><strong><?=$n?> pegawai</strong></div><progress value="<?=$n?>" max="<?=max(1,$educationTotal)?>" aria-label="<?=e($label)?>: <?=$n?> pegawai"></progress></div><?php endforeach; if(!$educationVisible): ?><p class="empty-analytics">Belum ada data pendidikan yang dapat ditampilkan pada pilihan ini.</p><?php endif ?></div><p id="education-coverage" class="insight-note"></p><p class="insight-note">Menggunakan nilai tersimpan di Admin, termasuk koreksi manual. Persentase dihitung dari data pendidikan yang terisi.</p></section>
<section id="panel-jobs" class="panel insight-panel" role="tabpanel" aria-labelledby="tab-jobs" tabindex="0" hidden><div class="insight-heading"><div><div class="eyebrow muted">PETA JABATAN</div><h2>Komposisi jabatan saat ini</h2><p class="subtle">Struktural, fungsional, dan pelaksana dalam satu pandangan.</p></div></div><div id="job-chart" class="distribution-chart"></div><div class="insight-heading"><h3>Rincian Kelompok Jabatan Fungsional</h3></div><div id="job-detail" class="distribution-chart analytics-detail"><?php public_render_job_details($analytics['all']['all']['job_details']); ?></div><p id="job-coverage" class="insight-note"></p><details class="insight-method"><summary>Aturan pengelompokan</summary><p>PLT diprioritaskan sebagai struktural dan dihitung sekali. Kepala dinas, sekretaris, kepala bidang, kepala subbagian, serta kepala UPTD/unit termasuk struktural. Fungsional dikenali dari jenjang dan rumpun jabatan yang tersedia; Mahir dan jenjang yang belum tercatat ditampilkan tersendiri. Jabatan lainnya masuk pelaksana. Jabatan kosong tidak dimasukkan ke diagram. Pengelompokan berdasarkan teks jabatan saat ini, bukan riwayat perubahan jabatan.</p></details></section>
<div id="demographic-empty" class="alert info" hidden>Belum ada pegawai pada status ini. Seluruh nilai ditampilkan sebagai 0.</div>
<noscript><p class="alert info">Ringkasan keseluruhan tetap ditampilkan. Aktifkan JavaScript untuk tab, filter, dan grafik analitik tambahan.</p></noscript>
</section>
<div class="public-note"><span aria-hidden="true">◉</span><p>Informasi publik dalam bentuk ringkasan.<br><span class="subtle">Dashboard menampilkan jumlah agregat tanpa direktori atau identitas individual pegawai.</span></p></div>
<?php page_bottom(); ?>
