-- Migrasi satu kali untuk database asli yang sudah diimpor.
-- Backup terlebih dahulu. Jangan jalankan setelah mengimpor SQL lengkap terbaru.
USE `kepegawaian_distapangtani`;

-- Nama lima kolom asli dipertahankan. Nomor menjadi AUTO_INCREMENT.
ALTER TABLE `pegawai_distapangtani`
  CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  MODIFY `no` int(11) NOT NULL AUTO_INCREMENT,
  ADD `mulai_asn_manual` date DEFAULT NULL COMMENT 'PPPK: tanggal 1 bulan pengangkatan, input manual',
  ADD `tanggal_lahir_manual` date DEFAULT NULL COMMENT 'Opsional untuk PJLP',
  ADD `jenis_kelamin_manual` enum('1','2') DEFAULT NULL COMMENT 'Opsional untuk PJLP',
  ADD `row_version` int unsigned NOT NULL DEFAULT 1,
  ADD `nip_unik` varchar(30) GENERATED ALWAYS AS
      (CASE WHEN `status_kepegawaian` = 'PJLP' THEN NULL ELSE REPLACE(`nip`, ' ', '') END) STORED,
  ADD UNIQUE KEY `uq_pegawai_nip` (`nip_unik`);

-- Satu-satunya tabel baru: akun admin beserta metadata keamanan login.
CREATE TABLE `admin` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `nama` varchar(100) NOT NULL,
  `username` varchar(40) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,
  `password_hash` varchar(255) NOT NULL,
  `role` enum('superadmin','admin') NOT NULL DEFAULT 'admin',
  `aktif` tinyint(1) NOT NULL DEFAULT 1,
  `auth_version` int unsigned NOT NULL DEFAULT 1,
  `failed_attempts` smallint unsigned NOT NULL DEFAULT 0,
  `locked_until` datetime DEFAULT NULL,
  `last_login` datetime DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_admin_username` (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `admin` (`nama`,`username`,`password_hash`,`role`,`aktif`)
VALUES ('Eric','Eric','$2b$12$qpDgdPx3AlI20J/jtQUyz.4rtY4DVh9HVx01C1ov5iN66tR/XcBJy','superadmin',1);

-- Pendidikan terakhir (termasuk dalam instalasi/migrasi versi terbaru).
ALTER TABLE `pegawai_distapangtani` ADD COLUMN `pendidikan_terakhir` ENUM('SD/sederajat','SMP/sederajat','SMA/sederajat','Diploma I - Diploma III','Diploma IV/Sarjana (S1)','Magister (S2)','Doktor (S3)','Program Profesi Dokter Hewan') DEFAULT NULL AFTER `jabatan`;
UPDATE `pegawai_distapangtani` SET `pendidikan_terakhir` = CASE
  WHEN UPPER(REPLACE(TRIM(`nama`),'.','')) REGEXP '(^|[,;[:space:]])(P[[:space:]]*H[[:space:]]*D|D[[:space:]]*P[[:space:]]*H[[:space:]]*I[[:space:]]*L)([,;[:space:]]+(A[[:space:]]*M[[:space:]]*D[[:space:]]*F[[:space:]]*A[[:space:]]*R[[:space:]]*M|S[[:space:]]*T[[:space:]]*R[[:space:]]*K[[:space:]]*E[[:space:]]*P|A[[:space:]]*M[[:space:]]*D[[:space:]]*K[[:space:]]*O[[:space:]]*M|A[[:space:]]*M[[:space:]]*D[[:space:]]*K[[:space:]]*E[[:space:]]*P|D[[:space:]]*P[[:space:]]*H[[:space:]]*I[[:space:]]*L|S[[:space:]]*F[[:space:]]*A[[:space:]]*R[[:space:]]*M|S[[:space:]]*S[[:space:]]*T[[:space:]]*A[[:space:]]*T|A[[:space:]]*M[[:space:]]*D[[:space:]]*A[[:space:]]*K|M[[:space:]]*K[[:space:]]*O[[:space:]]*M|M[[:space:]]*S[[:space:]]*O[[:space:]]*S|M[[:space:]]*H[[:space:]]*U[[:space:]]*M|M[[:space:]]*K[[:space:]]*E[[:space:]]*S|M[[:space:]]*E[[:space:]]*N[[:space:]]*G|S[[:space:]]*K[[:space:]]*O[[:space:]]*M|S[[:space:]]*S[[:space:]]*O[[:space:]]*S|S[[:space:]]*H[[:space:]]*U[[:space:]]*T|S[[:space:]]*K[[:space:]]*E[[:space:]]*P|S[[:space:]]*A[[:space:]]*R[[:space:]]*S|P[[:space:]]*H[[:space:]]*D|M[[:space:]]*S[[:space:]]*I|M[[:space:]]*A[[:space:]]*P|M[[:space:]]*P[[:space:]]*D|M[[:space:]]*A[[:space:]]*G|M[[:space:]]*K[[:space:]]*M|M[[:space:]]*B[[:space:]]*A|M[[:space:]]*S[[:space:]]*C|M[[:space:]]*P[[:space:]]*A|D[[:space:]]*R[[:space:]]*H|S[[:space:]]*P[[:space:]]*T|S[[:space:]]*A[[:space:]]*G|S[[:space:]]*P[[:space:]]*D|S[[:space:]]*T[[:space:]]*P|S[[:space:]]*K[[:space:]]*M|S[[:space:]]*I[[:space:]]*P|S[[:space:]]*A[[:space:]]*P|S[[:space:]]*I[[:space:]]*K|S[[:space:]]*S[[:space:]]*I|S[[:space:]]*A[[:space:]]*K|S[[:space:]]*D[[:space:]]*S|S[[:space:]]*T[[:space:]]*R|A[[:space:]]*M[[:space:]]*D|A[[:space:]]*M[[:space:]]*P|A[[:space:]]*M[[:space:]]*A|C[[:space:]]*P[[:space:]]*A|A[[:space:]]*P[[:space:]]*T|M[[:space:]]*M|M[[:space:]]*P|M[[:space:]]*T|M[[:space:]]*H|M[[:space:]]*A|M[[:space:]]*S|S[[:space:]]*P|S[[:space:]]*T|S[[:space:]]*E|S[[:space:]]*H|S[[:space:]]*S|I[[:space:]]*R|A[[:space:]]*K|C[[:space:]]*A|N[[:space:]]*S|G[[:space:]]*R))*[,;[:space:]]*$' THEN 'Doktor (S3)'
  WHEN UPPER(REPLACE(TRIM(`nama`),'.','')) REGEXP '(^|[,;[:space:]])(M[[:space:]]*S[[:space:]]*I|M[[:space:]]*M|M[[:space:]]*A[[:space:]]*P|M[[:space:]]*P|M[[:space:]]*P[[:space:]]*D|M[[:space:]]*K[[:space:]]*O[[:space:]]*M|M[[:space:]]*T|M[[:space:]]*H|M[[:space:]]*A[[:space:]]*G|M[[:space:]]*S[[:space:]]*O[[:space:]]*S|M[[:space:]]*H[[:space:]]*U[[:space:]]*M|M[[:space:]]*K[[:space:]]*E[[:space:]]*S|M[[:space:]]*K[[:space:]]*M|M[[:space:]]*B[[:space:]]*A|M[[:space:]]*S[[:space:]]*C|M[[:space:]]*E[[:space:]]*N[[:space:]]*G|M[[:space:]]*P[[:space:]]*A|M[[:space:]]*A|M[[:space:]]*S)([,;[:space:]]+(A[[:space:]]*M[[:space:]]*D[[:space:]]*F[[:space:]]*A[[:space:]]*R[[:space:]]*M|S[[:space:]]*T[[:space:]]*R[[:space:]]*K[[:space:]]*E[[:space:]]*P|A[[:space:]]*M[[:space:]]*D[[:space:]]*K[[:space:]]*O[[:space:]]*M|A[[:space:]]*M[[:space:]]*D[[:space:]]*K[[:space:]]*E[[:space:]]*P|D[[:space:]]*P[[:space:]]*H[[:space:]]*I[[:space:]]*L|S[[:space:]]*F[[:space:]]*A[[:space:]]*R[[:space:]]*M|S[[:space:]]*S[[:space:]]*T[[:space:]]*A[[:space:]]*T|A[[:space:]]*M[[:space:]]*D[[:space:]]*A[[:space:]]*K|M[[:space:]]*K[[:space:]]*O[[:space:]]*M|M[[:space:]]*S[[:space:]]*O[[:space:]]*S|M[[:space:]]*H[[:space:]]*U[[:space:]]*M|M[[:space:]]*K[[:space:]]*E[[:space:]]*S|M[[:space:]]*E[[:space:]]*N[[:space:]]*G|S[[:space:]]*K[[:space:]]*O[[:space:]]*M|S[[:space:]]*S[[:space:]]*O[[:space:]]*S|S[[:space:]]*H[[:space:]]*U[[:space:]]*T|S[[:space:]]*K[[:space:]]*E[[:space:]]*P|S[[:space:]]*A[[:space:]]*R[[:space:]]*S|P[[:space:]]*H[[:space:]]*D|M[[:space:]]*S[[:space:]]*I|M[[:space:]]*A[[:space:]]*P|M[[:space:]]*P[[:space:]]*D|M[[:space:]]*A[[:space:]]*G|M[[:space:]]*K[[:space:]]*M|M[[:space:]]*B[[:space:]]*A|M[[:space:]]*S[[:space:]]*C|M[[:space:]]*P[[:space:]]*A|D[[:space:]]*R[[:space:]]*H|S[[:space:]]*P[[:space:]]*T|S[[:space:]]*A[[:space:]]*G|S[[:space:]]*P[[:space:]]*D|S[[:space:]]*T[[:space:]]*P|S[[:space:]]*K[[:space:]]*M|S[[:space:]]*I[[:space:]]*P|S[[:space:]]*A[[:space:]]*P|S[[:space:]]*I[[:space:]]*K|S[[:space:]]*S[[:space:]]*I|S[[:space:]]*A[[:space:]]*K|S[[:space:]]*D[[:space:]]*S|S[[:space:]]*T[[:space:]]*R|A[[:space:]]*M[[:space:]]*D|A[[:space:]]*M[[:space:]]*P|A[[:space:]]*M[[:space:]]*A|C[[:space:]]*P[[:space:]]*A|A[[:space:]]*P[[:space:]]*T|M[[:space:]]*M|M[[:space:]]*P|M[[:space:]]*T|M[[:space:]]*H|M[[:space:]]*A|M[[:space:]]*S|S[[:space:]]*P|S[[:space:]]*T|S[[:space:]]*E|S[[:space:]]*H|S[[:space:]]*S|I[[:space:]]*R|A[[:space:]]*K|C[[:space:]]*A|N[[:space:]]*S|G[[:space:]]*R))*[,;[:space:]]*$' THEN 'Magister (S2)'
  WHEN UPPER(REPLACE(TRIM(`nama`),'.','')) REGEXP '((^|[,;[:space:]])(D[[:space:]]*R[[:space:]]*H)([,;[:space:]]+(A[[:space:]]*M[[:space:]]*D[[:space:]]*F[[:space:]]*A[[:space:]]*R[[:space:]]*M|S[[:space:]]*T[[:space:]]*R[[:space:]]*K[[:space:]]*E[[:space:]]*P|A[[:space:]]*M[[:space:]]*D[[:space:]]*K[[:space:]]*O[[:space:]]*M|A[[:space:]]*M[[:space:]]*D[[:space:]]*K[[:space:]]*E[[:space:]]*P|D[[:space:]]*P[[:space:]]*H[[:space:]]*I[[:space:]]*L|S[[:space:]]*F[[:space:]]*A[[:space:]]*R[[:space:]]*M|S[[:space:]]*S[[:space:]]*T[[:space:]]*A[[:space:]]*T|A[[:space:]]*M[[:space:]]*D[[:space:]]*A[[:space:]]*K|M[[:space:]]*K[[:space:]]*O[[:space:]]*M|M[[:space:]]*S[[:space:]]*O[[:space:]]*S|M[[:space:]]*H[[:space:]]*U[[:space:]]*M|M[[:space:]]*K[[:space:]]*E[[:space:]]*S|M[[:space:]]*E[[:space:]]*N[[:space:]]*G|S[[:space:]]*K[[:space:]]*O[[:space:]]*M|S[[:space:]]*S[[:space:]]*O[[:space:]]*S|S[[:space:]]*H[[:space:]]*U[[:space:]]*T|S[[:space:]]*K[[:space:]]*E[[:space:]]*P|S[[:space:]]*A[[:space:]]*R[[:space:]]*S|P[[:space:]]*H[[:space:]]*D|M[[:space:]]*S[[:space:]]*I|M[[:space:]]*A[[:space:]]*P|M[[:space:]]*P[[:space:]]*D|M[[:space:]]*A[[:space:]]*G|M[[:space:]]*K[[:space:]]*M|M[[:space:]]*B[[:space:]]*A|M[[:space:]]*S[[:space:]]*C|M[[:space:]]*P[[:space:]]*A|D[[:space:]]*R[[:space:]]*H|S[[:space:]]*P[[:space:]]*T|S[[:space:]]*A[[:space:]]*G|S[[:space:]]*P[[:space:]]*D|S[[:space:]]*T[[:space:]]*P|S[[:space:]]*K[[:space:]]*M|S[[:space:]]*I[[:space:]]*P|S[[:space:]]*A[[:space:]]*P|S[[:space:]]*I[[:space:]]*K|S[[:space:]]*S[[:space:]]*I|S[[:space:]]*A[[:space:]]*K|S[[:space:]]*D[[:space:]]*S|S[[:space:]]*T[[:space:]]*R|A[[:space:]]*M[[:space:]]*D|A[[:space:]]*M[[:space:]]*P|A[[:space:]]*M[[:space:]]*A|C[[:space:]]*P[[:space:]]*A|A[[:space:]]*P[[:space:]]*T|M[[:space:]]*M|M[[:space:]]*P|M[[:space:]]*T|M[[:space:]]*H|M[[:space:]]*A|M[[:space:]]*S|S[[:space:]]*P|S[[:space:]]*T|S[[:space:]]*E|S[[:space:]]*H|S[[:space:]]*S|I[[:space:]]*R|A[[:space:]]*K|C[[:space:]]*A|N[[:space:]]*S|G[[:space:]]*R))*[,;[:space:]]*$)|(^((PROF|H|HJ|IR|DRH)[[:space:]]+)*DRH[[:space:]]+[^[:space:]])' THEN 'Program Profesi Dokter Hewan'
  WHEN UPPER(REPLACE(TRIM(`nama`),'.','')) REGEXP '((^|[,;[:space:]])(S[[:space:]]*P|S[[:space:]]*P[[:space:]]*T|S[[:space:]]*K[[:space:]]*O[[:space:]]*M|S[[:space:]]*T|S[[:space:]]*E|S[[:space:]]*H|S[[:space:]]*A[[:space:]]*G|S[[:space:]]*S[[:space:]]*O[[:space:]]*S|S[[:space:]]*P[[:space:]]*D|S[[:space:]]*T[[:space:]]*P|S[[:space:]]*H[[:space:]]*U[[:space:]]*T|S[[:space:]]*K[[:space:]]*M|S[[:space:]]*I[[:space:]]*P|S[[:space:]]*A[[:space:]]*P|S[[:space:]]*I[[:space:]]*K|S[[:space:]]*S|S[[:space:]]*S[[:space:]]*I|S[[:space:]]*K[[:space:]]*E[[:space:]]*P|S[[:space:]]*F[[:space:]]*A[[:space:]]*R[[:space:]]*M|S[[:space:]]*A[[:space:]]*K|S[[:space:]]*D[[:space:]]*S|S[[:space:]]*S[[:space:]]*T[[:space:]]*A[[:space:]]*T|S[[:space:]]*A[[:space:]]*R[[:space:]]*S|S[[:space:]]*T[[:space:]]*R|S[[:space:]]*T[[:space:]]*R[[:space:]]*K[[:space:]]*E[[:space:]]*P|I[[:space:]]*R)([,;[:space:]]+(A[[:space:]]*M[[:space:]]*D[[:space:]]*F[[:space:]]*A[[:space:]]*R[[:space:]]*M|S[[:space:]]*T[[:space:]]*R[[:space:]]*K[[:space:]]*E[[:space:]]*P|A[[:space:]]*M[[:space:]]*D[[:space:]]*K[[:space:]]*O[[:space:]]*M|A[[:space:]]*M[[:space:]]*D[[:space:]]*K[[:space:]]*E[[:space:]]*P|D[[:space:]]*P[[:space:]]*H[[:space:]]*I[[:space:]]*L|S[[:space:]]*F[[:space:]]*A[[:space:]]*R[[:space:]]*M|S[[:space:]]*S[[:space:]]*T[[:space:]]*A[[:space:]]*T|A[[:space:]]*M[[:space:]]*D[[:space:]]*A[[:space:]]*K|M[[:space:]]*K[[:space:]]*O[[:space:]]*M|M[[:space:]]*S[[:space:]]*O[[:space:]]*S|M[[:space:]]*H[[:space:]]*U[[:space:]]*M|M[[:space:]]*K[[:space:]]*E[[:space:]]*S|M[[:space:]]*E[[:space:]]*N[[:space:]]*G|S[[:space:]]*K[[:space:]]*O[[:space:]]*M|S[[:space:]]*S[[:space:]]*O[[:space:]]*S|S[[:space:]]*H[[:space:]]*U[[:space:]]*T|S[[:space:]]*K[[:space:]]*E[[:space:]]*P|S[[:space:]]*A[[:space:]]*R[[:space:]]*S|P[[:space:]]*H[[:space:]]*D|M[[:space:]]*S[[:space:]]*I|M[[:space:]]*A[[:space:]]*P|M[[:space:]]*P[[:space:]]*D|M[[:space:]]*A[[:space:]]*G|M[[:space:]]*K[[:space:]]*M|M[[:space:]]*B[[:space:]]*A|M[[:space:]]*S[[:space:]]*C|M[[:space:]]*P[[:space:]]*A|D[[:space:]]*R[[:space:]]*H|S[[:space:]]*P[[:space:]]*T|S[[:space:]]*A[[:space:]]*G|S[[:space:]]*P[[:space:]]*D|S[[:space:]]*T[[:space:]]*P|S[[:space:]]*K[[:space:]]*M|S[[:space:]]*I[[:space:]]*P|S[[:space:]]*A[[:space:]]*P|S[[:space:]]*I[[:space:]]*K|S[[:space:]]*S[[:space:]]*I|S[[:space:]]*A[[:space:]]*K|S[[:space:]]*D[[:space:]]*S|S[[:space:]]*T[[:space:]]*R|A[[:space:]]*M[[:space:]]*D|A[[:space:]]*M[[:space:]]*P|A[[:space:]]*M[[:space:]]*A|C[[:space:]]*P[[:space:]]*A|A[[:space:]]*P[[:space:]]*T|M[[:space:]]*M|M[[:space:]]*P|M[[:space:]]*T|M[[:space:]]*H|M[[:space:]]*A|M[[:space:]]*S|S[[:space:]]*P|S[[:space:]]*T|S[[:space:]]*E|S[[:space:]]*H|S[[:space:]]*S|I[[:space:]]*R|A[[:space:]]*K|C[[:space:]]*A|N[[:space:]]*S|G[[:space:]]*R))*[,;[:space:]]*$)|(^((PROF|H|HJ|IR|DRH)[[:space:]]+)*IR[[:space:]]+[^[:space:]])' THEN 'Diploma IV/Sarjana (S1)'
  WHEN UPPER(REPLACE(TRIM(`nama`),'.','')) REGEXP '(^|[,;[:space:]])(A[[:space:]]*M[[:space:]]*D|A[[:space:]]*M[[:space:]]*D[[:space:]]*K[[:space:]]*O[[:space:]]*M|A[[:space:]]*M[[:space:]]*D[[:space:]]*K[[:space:]]*E[[:space:]]*P|A[[:space:]]*M[[:space:]]*D[[:space:]]*A[[:space:]]*K|A[[:space:]]*M[[:space:]]*D[[:space:]]*F[[:space:]]*A[[:space:]]*R[[:space:]]*M|A[[:space:]]*M[[:space:]]*P|A[[:space:]]*M[[:space:]]*A)([,;[:space:]]+(A[[:space:]]*M[[:space:]]*D[[:space:]]*F[[:space:]]*A[[:space:]]*R[[:space:]]*M|S[[:space:]]*T[[:space:]]*R[[:space:]]*K[[:space:]]*E[[:space:]]*P|A[[:space:]]*M[[:space:]]*D[[:space:]]*K[[:space:]]*O[[:space:]]*M|A[[:space:]]*M[[:space:]]*D[[:space:]]*K[[:space:]]*E[[:space:]]*P|D[[:space:]]*P[[:space:]]*H[[:space:]]*I[[:space:]]*L|S[[:space:]]*F[[:space:]]*A[[:space:]]*R[[:space:]]*M|S[[:space:]]*S[[:space:]]*T[[:space:]]*A[[:space:]]*T|A[[:space:]]*M[[:space:]]*D[[:space:]]*A[[:space:]]*K|M[[:space:]]*K[[:space:]]*O[[:space:]]*M|M[[:space:]]*S[[:space:]]*O[[:space:]]*S|M[[:space:]]*H[[:space:]]*U[[:space:]]*M|M[[:space:]]*K[[:space:]]*E[[:space:]]*S|M[[:space:]]*E[[:space:]]*N[[:space:]]*G|S[[:space:]]*K[[:space:]]*O[[:space:]]*M|S[[:space:]]*S[[:space:]]*O[[:space:]]*S|S[[:space:]]*H[[:space:]]*U[[:space:]]*T|S[[:space:]]*K[[:space:]]*E[[:space:]]*P|S[[:space:]]*A[[:space:]]*R[[:space:]]*S|P[[:space:]]*H[[:space:]]*D|M[[:space:]]*S[[:space:]]*I|M[[:space:]]*A[[:space:]]*P|M[[:space:]]*P[[:space:]]*D|M[[:space:]]*A[[:space:]]*G|M[[:space:]]*K[[:space:]]*M|M[[:space:]]*B[[:space:]]*A|M[[:space:]]*S[[:space:]]*C|M[[:space:]]*P[[:space:]]*A|D[[:space:]]*R[[:space:]]*H|S[[:space:]]*P[[:space:]]*T|S[[:space:]]*A[[:space:]]*G|S[[:space:]]*P[[:space:]]*D|S[[:space:]]*T[[:space:]]*P|S[[:space:]]*K[[:space:]]*M|S[[:space:]]*I[[:space:]]*P|S[[:space:]]*A[[:space:]]*P|S[[:space:]]*I[[:space:]]*K|S[[:space:]]*S[[:space:]]*I|S[[:space:]]*A[[:space:]]*K|S[[:space:]]*D[[:space:]]*S|S[[:space:]]*T[[:space:]]*R|A[[:space:]]*M[[:space:]]*D|A[[:space:]]*M[[:space:]]*P|A[[:space:]]*M[[:space:]]*A|C[[:space:]]*P[[:space:]]*A|A[[:space:]]*P[[:space:]]*T|M[[:space:]]*M|M[[:space:]]*P|M[[:space:]]*T|M[[:space:]]*H|M[[:space:]]*A|M[[:space:]]*S|S[[:space:]]*P|S[[:space:]]*T|S[[:space:]]*E|S[[:space:]]*H|S[[:space:]]*S|I[[:space:]]*R|A[[:space:]]*K|C[[:space:]]*A|N[[:space:]]*S|G[[:space:]]*R))*[,;[:space:]]*$' THEN 'Diploma I - Diploma III'
  ELSE NULL END WHERE `pendidikan_terakhir` IS NULL;
