<?php
require dirname(__DIR__).'/config.php'; require dirname(__DIR__).'/functions.php';
$admin=require_admin($pdo); $error=''; $open='';
$employee=['no'=>'','nama'=>'','nip'=>'','jabatan'=>'','status_kepegawaian'=>'PNS','mulai_asn_manual'=>'','tanggal_lahir_manual'=>'','jenis_kelamin_manual'=>'','row_version'=>1,'pendidikan_terakhir'=>'auto'];
$account=['id'=>'','nama'=>'','username'=>'','aktif'=>1,'auth_version'=>1];
if($_SERVER['REQUEST_METHOD']==='POST') {
    check_csrf(); $action=input('action');
    try {
        if($action==='save_employee') {
            foreach(array_keys($employee) as $key) if(isset($_POST[$key])) $employee[$key]=input($key); $employee['no']=input('id'); $open='employee-dialog';
            $data=validate_employee(array_map(fn($v)=>is_string($v)?$v:'',$_POST));
            $id=filter_var(input('id'),FILTER_VALIDATE_INT,['options'=>['min_range'=>1]]);
            if(input('id')!=='' && !$id) throw new DomainException('ID pegawai tidak valid.');
            if($id) {
                $q=$pdo->prepare('UPDATE pegawai_distapangtani SET nama=?,nip=?,jabatan=?,status_kepegawaian=?,mulai_asn_manual=?,tanggal_lahir_manual=?,jenis_kelamin_manual=?,pendidikan_terakhir=?,row_version=row_version+1 WHERE no=? AND row_version=?');
                $q->execute([...$data,$id,(int)input('row_version')]);
                if(!$q->rowCount()) throw new DomainException('Data telah berubah atau dihapus. Muat ulang sebelum mengedit kembali.');
            } else $pdo->prepare('INSERT INTO pegawai_distapangtani (nama,nip,jabatan,status_kepegawaian,mulai_asn_manual,tanggal_lahir_manual,jenis_kelamin_manual,pendidikan_terakhir) VALUES (?,?,?,?,?,?,?,?)')->execute($data);
            flash($id ? 'Data pegawai berhasil diperbarui.' : 'Pegawai baru berhasil ditambahkan.'); redirect('admin/');
        } elseif($action==='delete_employee') {
            $q=$pdo->prepare('DELETE FROM pegawai_distapangtani WHERE no=? AND row_version=?'); $q->execute([(int)input('id'),(int)input('row_version')]);
            if(!$q->rowCount()) throw new DomainException('Data telah berubah atau dihapus. Muat ulang tabel.');
            flash('Pegawai berhasil dihapus.'); redirect('admin/');
        } elseif(in_array($action,['save_admin','delete_admin','unlock_admin'],true)) {
            require_super($admin); $open='admin-dialog'; $id=(int)input('id');
            $pdo->beginTransaction();
            // Kunci semua akun dalam urutan tetap: otorisasi dan perlindungan superadmin atomik.
            $all=$pdo->query('SELECT * FROM admin ORDER BY id FOR UPDATE')->fetchAll(); $target=null;
            foreach($all as $a) if((int)$a['id']===$id) $target=$a;
            if($id && !$target) throw new DomainException('Admin tidak ditemukan.');
            if($target && (int)input('auth_version')!==(int)$target['auth_version']) throw new DomainException('Akun telah berubah. Muat ulang sebelum mencoba kembali.');
            if($action==='save_admin') {
                $account=['id'=>$id,'nama'=>input('nama_admin'),'username'=>input('username'),'aktif'=>input('aktif')==='1'?1:0,'auth_version'=>input('auth_version')];
                $password=password_input(); validate_account($account['nama'],$account['username'],$password,!$id);
                if($target && $target['role']==='superadmin' && ($account['username']!==$target['username'] || !$account['aktif'])) throw new DomainException('Username dan status aktif superadmin utama harus dipertahankan.');
                if($id) {
                    $hash=$password!=='' ? password_hash($password,PASSWORD_BCRYPT,['cost'=>12]) : $target['password_hash'];
                    $pdo->prepare('UPDATE admin SET nama=?,username=?,password_hash=?,aktif=?,auth_version=auth_version+1,failed_attempts=0,locked_until=NULL WHERE id=?')->execute([$account['nama'],$account['username'],$hash,$account['aktif'],$id]);
                    if($id===(int)$admin['id']) $_SESSION['auth_version']=(int)$target['auth_version']+1;
                } else $pdo->prepare("INSERT INTO admin (nama,username,password_hash,role,aktif) VALUES (?,?,?,'admin',?)")->execute([$account['nama'],$account['username'],password_hash($password,PASSWORD_BCRYPT,['cost'=>12]),$account['aktif']]);
            } elseif($action==='delete_admin') {
                if(!$target || $target['role']==='superadmin' || $id===(int)$admin['id']) throw new DomainException('Superadmin utama dan akun sendiri tidak dapat dihapus.');
                $pdo->prepare('DELETE FROM admin WHERE id=?')->execute([$id]);
            } else {
                if(!$target) throw new DomainException('Admin tidak ditemukan.');
                $pdo->prepare('UPDATE admin SET failed_attempts=0,locked_until=NULL WHERE id=?')->execute([$id]);
            }
            $pdo->commit(); flash('Manajemen admin berhasil disimpan.'); redirect('admin/?manage=1');
        } elseif($action==='change_password') {
            $open='password-dialog'; $old=isset($_POST['old_password']) && is_string($_POST['old_password'])?$_POST['old_password']:''; $new=password_input();
            if(!password_verify($old,$admin['password_hash'])) throw new DomainException('Password saat ini tidak sesuai.');
            validate_account($admin['nama'],$admin['username'],$new,true);
            $q=$pdo->prepare('UPDATE admin SET password_hash=?,auth_version=auth_version+1 WHERE id=? AND auth_version=?');
            $q->execute([password_hash($new,PASSWORD_BCRYPT,['cost'=>12]),$admin['id'],$admin['auth_version']]);
            if(!$q->rowCount()) throw new DomainException('Akun telah berubah. Silakan masuk kembali.');
            $_SESSION['auth_version']=(int)$admin['auth_version']+1; session_regenerate_id(true);
            flash('Password berhasil diganti. Sesi lain telah dicabut.'); redirect('admin/');
        } else { http_response_code(400); exit('Tindakan tidak valid.'); }
    } catch(DomainException $ex) {
        if($pdo->inTransaction()) $pdo->rollBack(); $error=$ex->getMessage(); http_response_code(422);
    } catch(PDOException $ex) {
        if($pdo->inTransaction()) $pdo->rollBack(); error_log($ex->getMessage());
        $error=$ex->getCode()==='23000' ? 'NIP/NIPPPK atau username sudah digunakan. Periksa kembali data Anda.' : 'Penyimpanan gagal. Silakan coba lagi.'; http_response_code(422);
    }
}
if($_SERVER['REQUEST_METHOD']==='GET' && isset($_GET['edit']) && is_string($_GET['edit'])) {
    $q=$pdo->prepare('SELECT * FROM pegawai_distapangtani WHERE no=?'); $q->execute([(int)$_GET['edit']]); $found=$q->fetch();
    if($found) { $employee=$found; $employee['mulai_asn_manual']=substr($employee['mulai_asn_manual']??'',0,7); $open='employee-dialog'; }
    else { $error='Pegawai tidak ditemukan.'; http_response_code(404); }
}
if($_SERVER['REQUEST_METHOD']==='GET' && isset($_GET['manage'])) {
    require_super($admin); $open='admin-dialog';
    if(isset($_GET['admin_edit']) && is_string($_GET['admin_edit'])) { $q=$pdo->prepare('SELECT id,nama,username,aktif,auth_version FROM admin WHERE id=?'); $q->execute([(int)$_GET['admin_edit']]); $found=$q->fetch(); if($found) $account=$found; }
}
$rows=$pdo->query('SELECT * FROM pegawai_distapangtani ORDER BY no')->fetchAll(); $counts=array_fill_keys(STATUSES,0); $incomplete=0;
foreach($rows as $r) { if(isset($counts[$r['status_kepegawaian']])) $counts[$r['status_kepegawaian']]++; if(str_starts_with($r['status_kepegawaian'],'PPPK') && !$r['mulai_asn_manual']) $incomplete++; }
$accounts=$admin['role']==='superadmin' ? $pdo->query('SELECT id,nama,username,role,aktif,auth_version,locked_until,last_login FROM admin ORDER BY id')->fetchAll() : [];
page_top('Admin',$admin,substr(hash('sha256',hash_file('sha256',dirname(__DIR__).'/style.css').hash_file('sha256',dirname(__DIR__).'/app.js')),0,12)); ?>
<section class="admin-heading"><div><div class="eyebrow muted">RUANG PENGELOLA · <?=e(date_id(new DateTimeImmutable('today')))?></div><h1>Kelola kepegawaian<span class="heading-dot">.</span></h1><p><?=e(APP_TITLE)?></p></div><div class="heading-actions"><button type="button" class="btn quiet" data-open="password-dialog">Ganti password</button><?php if($admin['role']==='superadmin'): ?><a href="<?=e(url('admin/?manage=1'))?>" class="btn outline">Kelola admin ↗</a><?php endif ?></div></section>
<?php show_flash(); if($error && !$open): ?><div class="alert error" role="alert"><?=e($error)?></div><?php endif ?>
<section class="stats compact"><article class="stat"><span class="subtle">Total pegawai</span><strong><?=count($rows)?></strong><span class="badge neutral">Seluruh status</span></article><?php foreach(STATUSES as $i=>$s): ?><article class="stat"><span class="subtle"><?=e($s)?></span><strong><?=$counts[$s]?></strong><span class="mini-line line-<?=$i?>"></span></article><?php endforeach ?></section>
<?php if($incomplete): ?><div class="alert info"><strong><?=$incomplete?> data PPPK perlu dilengkapi.</strong> Isi bulan dan tahun mulai ASN melalui tombol Edit. Bagian tengah NIPPPK tidak digunakan sebagai bulan pengangkatan.</div><?php endif ?>
<section class="panel directory"><div class="panel-heading"><div><h2>Daftar pegawai <span class="count"><?=count($rows)?></span></h2><p>Kelola identitas, jabatan, dan status dalam satu tempat.</p></div><span class="badge neutral">Akses privat</span></div><div class="toolbar"><label class="search"><span aria-hidden="true">⌕</span><input type="search" id="table-search" placeholder="Cari nama, NIP, atau jabatan…" aria-label="Cari pegawai"></label><label class="filter-label">Status <select id="status-filter"><option value="">Semua status</option><?php foreach(STATUSES as $s): ?><option><?=e($s)?></option><?php endforeach ?></select></label></div>
<div class="table-scroll"><table id="employee-table" class="admin-table"><thead><tr><th>No.</th><th>Nama pegawai</th><th>NIP / NIPPPK</th><th>Jabatan</th><th>Pendidikan terakhir</th><th>Status</th><th>Tanggal lahir</th><th>Usia</th><th>Mulai ASN</th><th>Usia awal ASN*</th><th>Jenis kelamin</th><th>Aksi</th></tr></thead><tbody><?php foreach($rows as $i=>$r): $info=employee_info($r); ?><tr data-status="<?=e($r['status_kepegawaian'])?>"><td class="subtle"><?=$i+1?></td><td><strong><?=e($r['nama'])?></strong></td><td class="nip"><?=e($info['nip'])?></td><td><?=e($r['jabatan']?:'-')?></td><td><?=e($r['pendidikan_terakhir']??'-')?></td><td><span class="badge status-<?=array_search($r['status_kepegawaian'],STATUSES,true)?>"><?=e($r['status_kepegawaian'])?></span></td><td class="nowrap"><?=e(date_id($info['dob']))?></td><td><?=e($info['age']??'-')?></td><td class="nowrap"><?php if(!$info['start'] && str_starts_with($r['status_kepegawaian'],'PPPK')): ?><span class="missing">Belum diisi</span><?php else: ?><?=e(date_id($info['start'],true))?><?php endif ?></td><td><?=e($info['start_age']??'-')?></td><td class="nowrap"><?=e($info['gender'])?><?= $info['gender_code'] ? ' ('.e($info['gender_code']).')' : '' ?></td><td><div class="row-actions"><a class="btn small outline" href="<?=e(url('admin/?edit='.$r['no']))?>">Edit</a><form method="post" action="<?=e(url('admin/'))?>" data-confirm="Hapus pegawai <?=e($r['nama'])?>? Tindakan ini tidak dapat dibatalkan."><?=csrf_field()?><input type="hidden" name="action" value="delete_employee"><input type="hidden" name="id" value="<?=$r['no']?>"><input type="hidden" name="row_version" value="<?=$r['row_version']?>"><button class="btn small danger" type="submit">Hapus</button></form></div></td></tr><?php endforeach ?></tbody></table><div id="empty-state" class="empty" hidden>Tidak ada pegawai yang sesuai pencarian.</div></div>
<div class="table-footer"><span id="table-info" aria-live="polite"></span><div class="pagination"><button id="prev-page" class="btn quiet" type="button">← Sebelumnya</button><span id="page-info"></span><button id="next-page" class="btn quiet" type="button">Berikutnya →</button></div></div><div class="add-row"><span>* Usia awal ASN dihitung pada tanggal 1 bulan pengangkatan.</span><button type="button" class="btn primary" data-open="employee-dialog" data-new-employee>＋ Tambah pegawai</button></div></section>
<dialog id="employee-dialog" <?= $open==='employee-dialog'?'data-auto-open':'' ?>><div class="dialog-heading"><div><div class="eyebrow muted">DATA KEPEGAWAIAN</div><h2 id="employee-form-title"><?=$employee['no']?'Edit':'Tambah'?> pegawai</h2></div><button type="button" class="icon-btn" data-close aria-label="Tutup">×</button></div><?php if($error && $open==='employee-dialog'): ?><div class="alert error" role="alert"><?=e($error)?></div><?php endif ?>
<form method="post" action="<?=e(url('admin/'))?>" id="employee-form"><?=csrf_field()?><input type="hidden" name="action" value="save_employee"><input type="hidden" name="id" value="<?=e($employee['no'])?>"><input type="hidden" name="row_version" value="<?=e($employee['row_version'])?>"><div class="form-grid"><label class="span-two">Nama lengkap<input name="nama" required maxlength="150" value="<?=e($employee['nama'])?>"></label><label class="span-two">Jabatan<input name="jabatan" maxlength="255" value="<?=e($employee['jabatan'])?>"></label><label class="span-two">Pendidikan terakhir<select name="pendidikan_terakhir" id="employee-education" data-patterns="<?=e(json_encode(EDUCATION_PATTERNS,JSON_THROW_ON_ERROR))?>"><option value="auto" <?=empty($employee['pendidikan_terakhir']) || $employee['pendidikan_terakhir']==='auto'?'selected':''?>>Otomatis dari gelar pada nama</option><?php foreach(EDUCATION_LEVELS as $level): ?><option value="<?=e($level)?>" <?=($employee['pendidikan_terakhir']??null)===$level?'selected':''?>><?=e($level)?></option><?php endforeach ?></select><small id="education-preview" aria-live="polite">Jika gelar tidak dikenali, pilih pendidikan sesuai ijazah. Pilihan manual lebih diutamakan.</small></label><label class="span-two">Status kepegawaian<select name="status_kepegawaian" id="employee-status"><?php foreach(STATUSES as $s): ?><option <?=$employee['status_kepegawaian']===$s?'selected':''?>><?=e($s)?></option><?php endforeach ?></select></label><label id="nip-field" class="span-two"><span id="nip-label">NIP</span><input name="nip" id="employee-nip" inputmode="numeric" maxlength="24" value="<?=e($employee['nip'])?>" aria-describedby="nip-hint"><small id="nip-hint">18 digit; spasi akan dihapus otomatis.</small></label><label id="asn-field" class="span-two" hidden>Bulan dan tahun mulai ASN<input type="month" name="mulai_asn_manual" value="<?=e($employee['mulai_asn_manual'])?>" max="<?=date('Y-m')?>"><small>Isi sesuai dokumen pengangkatan PPPK.</small></label><label class="pjlp-field" hidden>Tanggal lahir (opsional)<input type="date" name="tanggal_lahir_manual" value="<?=e($employee['tanggal_lahir_manual'])?>" max="<?=date('Y-m-d')?>"></label><label class="pjlp-field" hidden>Jenis kelamin (opsional)<select name="jenis_kelamin_manual"><option value="">Belum diisi</option><option value="1" <?=$employee['jenis_kelamin_manual']==='1'?'selected':''?>>Laki-laki</option><option value="2" <?=$employee['jenis_kelamin_manual']==='2'?'selected':''?>>Perempuan</option></select></label></div><div class="preview-info" id="nip-preview" aria-live="polite">Tanggal lahir dan jenis kelamin akan dihitung dari nomor pegawai.</div><div class="dialog-actions"><button type="button" class="btn quiet" data-close>Batal</button><button class="btn primary" type="submit">Simpan pegawai</button></div></form></dialog>
<?php if($admin['role']==='superadmin'): ?><dialog id="admin-dialog" class="wide-dialog" <?=$open==='admin-dialog'?'data-auto-open':''?>><div class="dialog-heading"><div><div class="eyebrow muted">OTORITAS SUPERADMIN</div><h2>Manajemen admin</h2></div><button type="button" class="icon-btn" data-close aria-label="Tutup">×</button></div><?php if($error && $open==='admin-dialog'): ?><div class="alert error" role="alert"><?=e($error)?></div><?php endif ?>
<div class="table-scroll"><table><thead><tr><th>Admin</th><th>Hak akses</th><th>Status</th><th>Aksi</th></tr></thead><tbody><?php foreach($accounts as $a): ?><tr><td><strong><?=e($a['nama'])?></strong><small class="block"><?=e($a['username'])?></small></td><td><?=e($a['role'])?></td><td><?= $a['aktif']?'Aktif':'Nonaktif' ?><?= $a['locked_until'] && strtotime($a['locked_until'])>time()?' · Terkunci':'' ?></td><td><div class="row-actions"><a class="btn small outline" href="<?=e(url('admin/?manage=1&admin_edit='.$a['id']))?>">Edit</a><?php if($a['role']!=='superadmin'): ?><form method="post" action="<?=e(url('admin/'))?>" data-confirm="Hapus akun admin ini?"><?=csrf_field()?><input type="hidden" name="action" value="delete_admin"><input type="hidden" name="id" value="<?=$a['id']?>"><input type="hidden" name="auth_version" value="<?=$a['auth_version']?>"><button class="btn small danger">Hapus</button></form><?php endif; if($a['locked_until']): ?><form method="post" action="<?=e(url('admin/'))?>"><?=csrf_field()?><input type="hidden" name="action" value="unlock_admin"><input type="hidden" name="id" value="<?=$a['id']?>"><input type="hidden" name="auth_version" value="<?=$a['auth_version']?>"><button class="btn small quiet">Buka kunci</button></form><?php endif ?></div></td></tr><?php endforeach ?></tbody></table></div>
<form class="admin-account-form" method="post" action="<?=e(url('admin/'))?>"><?=csrf_field()?><input type="hidden" name="action" value="save_admin"><input type="hidden" name="id" value="<?=e($account['id'])?>"><input type="hidden" name="auth_version" value="<?=e($account['auth_version'])?>"><h3><?=$account['id']?'Edit':'Tambah'?> admin</h3><div class="form-grid"><label>Nama admin<input name="nama_admin" maxlength="100" required value="<?=e($account['nama'])?>"></label><label>Username<input name="username" required minlength="3" maxlength="40" pattern="[A-Za-z0-9_.\-]{3,40}" value="<?=e($account['username'])?>" autocomplete="off"></label><label>Password <?=$account['id']?'baru (opsional)':''?><input name="password" type="password" minlength="10" maxlength="72" <?=$account['id']?'':'required'?> autocomplete="new-password"><small>10–72 byte. Kosongkan saat edit untuk mempertahankan password.</small></label><label>Status<select name="aktif"><option value="1" <?=$account['aktif']?'selected':''?>>Aktif</option><option value="0" <?=!$account['aktif']?'selected':''?>>Nonaktif</option></select></label></div><div class="dialog-actions"><?php if($account['id']): ?><a class="btn quiet" href="<?=e(url('admin/?manage=1'))?>">Batal edit</a><?php endif ?><button class="btn primary" type="submit">Simpan admin</button></div></form></dialog><?php endif ?>
<dialog id="password-dialog" <?=$open==='password-dialog'?'data-auto-open':''?>><div class="dialog-heading"><h2>Ganti password</h2><button type="button" class="icon-btn" data-close aria-label="Tutup">×</button></div><?php if($error && $open==='password-dialog'): ?><div class="alert error" role="alert"><?=e($error)?></div><?php endif ?><form method="post" action="<?=e(url('admin/'))?>"><?=csrf_field()?><input type="hidden" name="action" value="change_password"><label>Password saat ini<input type="password" name="old_password" required autocomplete="current-password"></label><label>Password baru<input type="password" name="password" required minlength="10" maxlength="72" autocomplete="new-password"></label><div class="dialog-actions"><button type="button" class="btn quiet" data-close>Batal</button><button class="btn primary">Simpan password</button></div></form></dialog>
<?php page_bottom(); ?>
